FROM	alpine

RUN		apk update
RUN		apk add grafana

RUN		apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache

COPY	/srcs/telegraf.conf			/etc/telegraf/
COPY	/srcs/start.sh				/
COPY	/srcs/grafana.db			/usr/share/grafana/data/

WORKDIR	/usr/share/grafana

EXPOSE	3000

ENTRYPOINT	sh /start.sh

