FROM	alpine

RUN		apk update
RUN		apk add --no-cache wget php7 php7-fpm php7-mysqli php7-mbstring php7-json php7-session
RUN		apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache
RUN		mkdir -p /usr/share/webapps/ 
RUN		cd /usr/share/webapps/

RUN     wget https://ru.wordpress.org/latest-ru_RU.tar.gz
RUN		tar -xzvf latest-ru_RU.tar.gz
RUN		mkdir -p /var/www
RUN		mv wordpress /var/www/

RUN		apk add --no-cache nginx openssl php7-common php7-iconv php7-gd php7-curl php7-xml php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom 
RUN		rm -f /etc/nginx/conf.d/default.conf
RUN		mkdir -p /run/nginx

RUN		mkdir /etc/nginx/ssl 
RUN		openssl genrsa -out /etc/nginx/ssl/private.key 2048 
RUN 	openssl req -new -key /etc/nginx/ssl/private.key -out /etc/nginx/ssl/server.csr -subj "/C=RU/ST=Russia/L=Kazan/O=42 School/OU=jmontagu/CN=localhost"
RUN		openssl x509 -days 365 -req -signkey /etc/nginx/ssl/private.key -in /etc/nginx/ssl/server.csr -out /etc/nginx/ssl/server.crt

COPY	/srcs/nginx.conf			/etc/nginx/conf.d/default.conf

COPY	/srcs/telegraf.conf			/etc/telegraf/
COPY	/srcs/start.sh				/
COPY	/srcs/wp-config.php			/var/www/wordpress/

EXPOSE	5050

ENTRYPOINT sh start.sh
